version: 0.0.{build}
skip_tags: true
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- ps: >-
    chcp 65001

    nuget restore

    msbuild "C:\projects\naratmal\나랏말.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:GeneratePackageOnBuild=false
deploy:
- provider: NuGet
  api_key:
    secure: dgSmducMCHthwTqmWf71Rg61xUkGYSHHJLpvIXtcS17rSpdfoSqKSy0QnCZr9AzQ
  on:
    branch: master